version: '3'
services:
  backend-test:
    build: 
      context: ../
      dockerfile: docker/Dockerfile.test
      args:
        port: ${PORT}
    env_file:
      - ../.env
    environment:
      WAIT_HOSTS: database-test:27017
  database-test:
    image: postgres
    env_file:
      - ../.env
    volumes:
      - ".${POSTGRES_TEST_DATA_DIR}:${POSTGRES_TEST_DATA_DIR}"
    expose:
      - 27017
